name: coffeshop
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #google_maps_flutter: ^0.5.7
  flutter_map: any
  latlong: ^0.6.1
  qrcode_reader: ^0.4.4
  unicorndial: ^1.1.5
  font_awesome_flutter: ^8.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/starbucks.jpg
  - images/expresso.jpg
  - images/espresso.jpg
  - images/brewed.jpg
  - images/bootledrink.jpg
  - images/hotchoco.jpg
  - images/icedtea.jpg
  - images/hottea.jpg
  - images/blended.jpg
  - images/icedcoffee.jpg
  - images/bakery.jpg
  - images/hotbreak.jpg
  - images/lunch.jpg
  - images/freshfruit.jpg
  - images/snacks.jpg
  - images/wholebean.jpg
  - images/escapsule.jpg
  - images/shopbag.jpg
  - images/caffamericano.jpg
  - images/caflatte.jpg
  - images/caramelmachiato.jpg
  - images/classicecapp.jpg
  - images/coldfoamiceapp.jpg
  - images/espressomahciato.jpg
  - images/flatwhite.jpg
  - images/icedcaflatte.jpg
  - images/icedwhitechocomocha.jpg
  - images/lattemachiato.jpg
  - images/whitechocomocha.jpg
  - images/caflattebig.jpg
  - images/oahead.jpg
  - images/cc0.png
  - images/cc1.png
  - images/cc2.png
  - images/cc3.png
  - images/cc4.png
  - images/cc5.png
  - images/cc6.png
  - images/cc7.png
  - images/cc8.png
  - images/cc9.png
  - images/cc10.png
  - images/cc11.png
  - images/cc12.png
  - images/lcard.jpg
  - images/logback.jpg
  - images/pwalkicon.png
  - images/ccupicon.png
  - images/ordericon.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: Greatvibes
      fonts:
        - asset: fonts/GreatVibes-Regular.ttf
    - family: Playball
      fonts:
        - asset: fonts/Playball-Regular.ttf
    - family: Merienda
      fonts:
        - asset: fonts/Merienda-Regular.ttf
        - asset: fonts/Merienda-Bold.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
